# Generated by Django 5.2 on 2025-07-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.IntegerField(primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=250)),
                ('acronim', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'course_semester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSemesterTasks',
            fields=[
                ('pk', models.CompositePrimaryKey('id_task', 'id_course', 'id_semester', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_semester_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'course_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'course_teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('pk', models.CompositePrimaryKey('id_grade', 'id_course', 'id_student', 'id_task', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_grade', models.IntegerField()),
                ('id_course', models.IntegerField()),
                ('id_student', models.IntegerField()),
                ('id_task', models.IntegerField()),
                ('grade', models.DecimalField(decimal_places=1, max_digits=1)),
                ('number_tries', models.IntegerField()),
                ('results', models.CharField(max_length=255)),
                ('delivery_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('name_role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id_semester', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'semester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id_task', models.IntegerField(primary_key=True, serialize=False)),
                ('id_course_semester', models.IntegerField()),
                ('task_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('speciality_field', models.CharField(db_column='speciality ', max_length=250)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
    ]
